SELECT 
	DISTINCT OH.ORDER_ID ,
	OH.STATUS_ID ,
	FC.FACILITY_ID ,
	FC.FACILITY_NAME ,
	FC.FACILITY_TYPE_ID
FROM
	ORDER_HEADER OH
LEFT JOIN ORDER_SHIPMENT OS
ON
	OH.ORDER_ID = OS.ORDER_ID
	AND OH.STATUS_ID IN ('ORDER_CREATED', 'ORDER_APPROVED')
JOIN SHIPMENT SH
ON
	SH.SHIPMENT_ID = OS.SHIPMENT_ID
JOIN FACILITY FC
ON
	FC.FACILITY_ID = SH.ORIGIN_FACILITY_ID