
select 
	P.PRODUCT_ID,
	P.INTERNAL_NAME ,
	COUNT(P.PRODUCT_ID) as TOTAL_QUANTITY_SOLD,
	SUM(OI.QUANTITY * OI.UNIT_PRICE) TOTAL_REVENUE,
	PA.CITY 
from order_item OI
join product P
on OI.PRODUCT_ID = P.PRODUCT_ID 
left join order_contact_mech OCM
on OCM.ORDER_ID = OI.ORDER_ID and OCM.CONTACT_MECH_PURPOSE_TYPE_ID = 'SHIPPING_LOCATION'
join postal_address PA
on PA.CONTACT_MECH_ID = OCM.CONTACT_MECH_ID and PA.CITY = 'New York'
group by P.PRODUCT_ID
order by SUM(OI.QUANTITY * OI.UNIT_PRICE) desc, COUNT(P.PRODUCT_ID) desc
