select 
	COUNT(OH.ORDER_ID) as TOTAL_ORDERS,
	OH.SALES_CHANNEL_ENUM_ID as SALES_CHANNEL,
	SUM(OH.GRAND_TOTAL) as TOTAL_REVENUE,
	DATE(MIN(OH.ORDER_DATE)) AS FROM_DATE,
	DATE(MAX(OH.ORDER_DATE)) AS TO_DATE
from order_header OH
group by OH.SALES_CHANNEL_ENUM_ID