SELECT
	II.PRODUCT_ID ,
	II.FACILITY_ID ,
	II.INVENTORY_ITEM_ID ,
	ID.REASON_ENUM_ID AS REASON_CODE,
	ABS(IV.QUANTITY_ON_HAND_VAR) AS QUANTITY_LOST_OR_DAMAGED,
	ID.EFFECTIVE_DATE AS TRANSACTION_DATE
FROM
	INVENTORY_ITEM II
JOIN INVENTORY_ITEM_VARIANCE IV
ON
	IV.INVENTORY_ITEM_ID = II.INVENTORY_ITEM_ID
JOIN INVENTORY_ITEM_DETAIL ID
ON
	ID.INVENTORY_ITEM_ID = II.INVENTORY_ITEM_ID
	AND ID.PHYSICAL_INVENTORY_ID = IV.PHYSICAL_INVENTORY_ID
	AND ID.REASON_ENUM_ID IS NOT null
