SELECT 
	OS.ORDER_ID ,
	OS.ORDER_ITEM_SEQ_ID ,
	OS2.STATUS_ID AS CURR_STATUS,
	OS.STATUS_ID AS PREV_STATUS,
	OS2.CHANGE_REASON_ENUM_ID
FROM
	ORDER_STATUS OS
JOIN ORDER_STATUS OS2
ON
	OS.ORDER_ITEM_SEQ_ID = OS2.ORDER_ITEM_SEQ_ID
	AND OS.ORDER_ID = OS2.ORDER_ID
	AND OS2.STATUS_DATETIME > OS.STATUS_DATETIME
