SELECT
	P.PRODUCT_ID ,
	FC.FACILITY_ID ,
	II.QUANTITY_ON_HAND_TOTAL AS QOH,
	II.AVAILABLE_TO_PROMISE_TOTAL AS ATP,
	(II.QUANTITY_ON_HAND_TOTAL - II.AVAILABLE_TO_PROMISE_TOTAL) AS DIFFERENCE
FROM
	PRODUCT P
JOIN INVENTORY_ITEM II
ON
	II.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN FACILITY FC
ON
	FC.FACILITY_ID = II.FACILITY_ID